---
title: blog 4.0
baseurl: "/Minimal-Text"
desc: A minimal blog for off-topic blog entries.
about: My 4th attemp at creating the second blog for the MDS
image: https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/70186327_10157403921631101_9120830809354272768_n.jpg?_nc_cat=104&_nc_oc=AQlgwtLm0mOrz3A6QgvNBvRcCT9IXnkHd6l2EAQ6jHanoiXSQEqxAX-2YhIdHIHPYk0&_nc_ht=scontent-sea1-1.xx&oh=6c5f76816c0fabdce38c6d26599e2379&oe=5E36F1A8
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
